gocsaf/csaf

cmd/csaf_provider/controller.go, cmd/csaf_provider/extract.go, cmd/csaf_provider/files.go, cmd/csaf_provider/transaction.go, csaf/models.go, csaf/rolie.go
=> Fix golint warnings.

cmd/csaf_provider/config.go, cmd/csaf_provider/controller.go, cmd/csaf_provider/create.go, cmd/csaf_provider/files.go, cmd/csaf_provider/tmpl/upload.html, cmd/csaf_provider/transaction.go, csaf/models.go, csaf/rolie.go
Add a `dynamic_provider_metadata` bool flag in configuration to update the meta data file dynamical on each upload.
The publisher is taken from the config, too.
=> Static metadata

cmd/csaf_uploader/main.go, go.mod, go.sum
This PR implements a command line tool to upload CSAF documents to the trusted provider.
=> CSAF uploader

cmd/csaf_uploader/main.go
* Added flag to uploader to upload pre-signed CSAF files.
* Check against CSAF JSON schema before uploading. Added flag to prevent this,
=> Upload external signatures

util/file.go
Forget to add a copyright header.
=> Added missing copyright header

cmd/csaf_checker/checks.go, cmd/csaf_checker/main.go, cmd/csaf_checker/report.go, cmd/csaf_checker/tmpl/report.html, cmd/csaf_provider/actions.go, cmd/csaf_provider/config.go, cmd/csaf_provider/create.go, cmd/csaf_uploader/main.go, csaf/models.go, csaf/schema/provider_json_schema.json, csaf/validation.go
WIP: Add checker for CSAF trusted provider.
=> Csaf checker

cmd/csaf_checker/processor.go, cmd/csaf_checker/reporters.go
Second part of the Fix of issue #24.
=> Do not report success on checks which were not performed.

csaf/validation.go
=> Fixed issue #37

Makefile, README.md
* Makefile with the following targets
** build for (linux system)
** build_win  (windows system)
** build_tag (build from the last tag)
** clean  for (removing the binaries)
* Adjust README file
=> Add Makefile for building go components

cmd/csaf_checker/processor.go
=> Checker locate provider metadata json

cmd/csaf_provider/actions.go
=> Improve error message of missing tlp

cmd/csaf_checker/processor.go, cmd/csaf_provider/actions.go, csaf/rolie.go
Add extra layer of `{ "feed": { ... } }` around the generated ROLIE documents,
=> Add another layer aound the ROLIE feed documents.

docs/provider-setup.md
There was a weird wording. I guess it comes from resolving a merge conflict...
=> Correct double line

csaf/schema/csaf_json_schema.json, csaf/schema/provider_json_schema.json
- resolves csaf-poc/csaf_distribution#97
- add strict schemas from OASIS repo
=> CSD02 Schema update

cmd/csaf_aggregator/indices.go
=> ROLIE link

cmd/csaf_checker/processor.go, csaf/models.go
* Replace "pgp_keys" with "public_openpgp_key"
=> Fix one attribute by writing provider-metadata.json

Makefile
* Using a simple combined recipe to create to dist directories for
a release archive with all docs.
=> Add dist Makefile target

csaf/summary.go, util/json.go
Simplifies the mass extraction via JSONPath from a document.
=> Jsonpath matcher

cmd/csaf_uploader/main.go
* Add an exit code if an upload failed, but also print all the messages
as before.
=> Improve exit code for failed upload

cmd/csaf_provider/main.go
=> Improve error-handling by wrong config values.

docs/csaf_aggregator.md, docs/csaf_checker.md, docs/csaf_provider.md, docs/csaf_uploader.md, docs/examples/aggregator.toml
* Add basic aggregator docs, including a crontab example.
* Update user docs for the other command, using the --help output.
=> Improve user documentation

cmd/csaf_checker/processor.go, csaf/schema/ROLIE_feed_json_schema.json, csaf/validation.go
=> Validation against ROLIE json schema  

cmd/csaf_aggregator/mirror.go, cmd/csaf_checker/processor.go, cmd/csaf_provider/actions.go, cmd/csaf_uploader/main.go, util/file.go, util/file_test.go
Only allow uploads of validated filenames.
=> clean filenames to adhere standard

cmd/csaf_aggregator/indices.go, cmd/csaf_provider/actions.go
Add "category" to ROLIE feed: Resolves issue #41
=> Add missing category list in ROLIE feeds. Resolves issue #41

cmd/csaf_uploader/main.go, go.mod, go.sum
Replaced deprecated import with recent one.
=> Replace deprecated terminal import.

cmd/csaf_aggregator/config.go, cmd/csaf_checker/main.go, cmd/csaf_checker/processor.go, csaf/util.go, docs/csaf_aggregator.md, docs/csaf_checker.md, util/client.go
* Add log output for fetching index.txt and changes.csv.
=> Improve checker diagnostics

cmd/csaf_aggregator/config.go, cmd/csaf_aggregator/mirror.go, cmd/csaf_provider/actions.go, cmd/csaf_provider/config.go, cmd/csaf_provider/create.go, docs/csaf_aggregator.md, docs/csaf_provider.md, docs/scripts/setupProviderForITest.sh
Create openpg folders with copies of the public keys. Solves issue #85.
=> Openpgp folder

cmd/csaf_checker/links.go, cmd/csaf_checker/processor.go, cmd/csaf_checker/report.go, cmd/csaf_checker/reporters.go, cmd/csaf_checker/tmpl/report.html
Added types to checker messages.
=> Added types to checker messages.

csaf/models.go
=> New provider metadata role defaults to trusted now.

cmd/csaf_checker/processor.go, csaf/models.go
consider fingerprints case-in-sensitive equal.
=> use equal fold to compare fingerprints.

cmd/csaf_checker/processor.go, cmd/csaf_checker/report.go, cmd/csaf_checker/tmpl/report.html
=> Report date

cmd/csaf_aggregator/full.go, cmd/csaf_aggregator/indices.go, cmd/csaf_provider/actions.go
=> Fix datetime format

cmd/csaf_checker/processor.go, csaf/rolie.go
=> Integrity check the ROLIE feed advisory URLs, hashes and signatures.

cmd/csaf_checker/reporters.go
Changes output if security.txt was found to solve https://github.com/csaf-poc/csaf_distribution/issues/195
=> Changes phrasing of output from csaf_checker if security.txt was found

docs/csaf_checker.md
Solves https://github.com/csaf-poc/csaf_distribution/issues/165
=> Adds explanation of type returns of individual checkers to csaf_checker.md

cmd/csaf_checker/processor.go, cmd/csaf_checker/reporters.go
Solves https://github.com/csaf-poc/csaf_distribution/issues/202 and also fixes issue where redirects were listed in part and total.
=> Trimmed redirects

docs/csaf_downloader.md
The title of the .md file should be csaf_downloader, not "uploader". Also added an introductory sentence.
=> Correcting documentation

cmd/csaf_aggregator/indices.go, cmd/csaf_checker/processor.go, cmd/csaf_provider/indices.go
=> Fields in changes.csv were swapped.

docs/csaf_provider.md, docs/examples/config.toml, docs/examples/provider_config.toml
Co-authored by mfd2007. Rewritten since a seperate file has been created, that provider.md now references.
=> Provider toml

cmd/csaf_checker/processor.go, cmd/csaf_checker/report.go, cmd/csaf_checker/tmpl/report.html
=> Added publisher and role to domain report.

cmd/csaf_aggregator/mirror.go, cmd/csaf_checker/processor.go, cmd/csaf_downloader/downloader.go, csaf/advisories.go
=> Ignore bad URLs in index.txt

cmd/csaf_aggregator/mirror.go
=> Create valid uppercase TLPs.

docs/scripts/setupProviderForITest.sh, docs/scripts/testAggregator.sh, docs/scripts/testDownloader.sh
* Add a simple aggegator web server config.
* Add a downloader test using a direct url from the aggregator.
=> Improve integration test scripts

cmd/csaf_uploader/main.go
Fixes not-yet-fixed of https://github.com/csaf-poc/csaf_distribution/issues/207
=> Handle none JSON replies to uploader calls as errors.

csaf/util.go
=> Do not silence errors when fetching a pmd

docs/examples/aggregator.toml
Update names of config options and add new options.
=> Update config option

cmd/csaf_checker/processor.go
Solves #160 
Improves handling of index.txt/changes.csv if either are missing or empty. Gives info to user if directory listings are missing.
=> Find missing

cmd/csaf_checker/processor.go
Remove ROLIE index.txt, changes.csv support in scanner.
=> There are no index.txt, changes.csv in ROLIE dists.

cmd/csaf_aggregator/mirror.go, cmd/csaf_checker/processor.go, cmd/csaf_provider/create.go, csaf/advisories.go, csaf/models.go, util/json.go
=> Directory url

cmd/csaf_aggregator/config.go, cmd/csaf_aggregator/interim.go, cmd/csaf_aggregator/lazytransaction.go
Reworked interim mode in aggregator.
Solves #274
Solves #273
=> Rework interim

cmd/csaf_aggregator/config.go, cmd/csaf_aggregator/full.go, csaf/models.go
Add support for publishers in aggregator.
Fixes #276
=> Aggregator publishers

docs/csaf_aggregator.md
Add documentation for new option "update_interval" and behavior from #278.
=> Add documention for update_interval

docs/csaf_provider.md, docs/csaf_uploader.md
=> Create once docs

README.md, cmd/csaf_checker/processor.go, cmd/csaf_checker/reporters.go, docs/csaf_uploader.md
Now checks requirements 8-10 in one function. This allows to evalue their success based on the overall result.
Fixes https://github.com/csaf-poc/csaf_distribution/issues/201 and fixes https://github.com/csaf-poc/csaf_distribution/issues/220
=> Checker810

cmd/csaf_aggregator/processor.go, cmd/csaf_checker/processor.go, cmd/csaf_downloader/downloader.go, csaf/util.go
=> Invalid pmds are invalid.

util/json.go
=> Return error if parsing time string failed.

cmd/csaf_uploader/main.go
=> Uploader: Log the filename too, if an upload fails. 

cmd/csaf_checker/main.go, cmd/csaf_checker/processor.go, docs/csaf_checker.md
This PR adds support for remote validation to the checker.
This partly resolves #300
=> Add remote validator support to checker

README.md, cmd/csaf_validator/main.go, docs/csaf_validator.md
Add a `csaf_validator` tool.
Resolves #258
=> Add csaf_validator

cmd/csaf_checker/processor.go, cmd/csaf_downloader/downloader.go
=> Warn in checker and downloader if advisories are delivered as none JSON

cmd/csaf_aggregator/mirror.go, cmd/csaf_checker/processor.go, cmd/csaf_checker/reporters.go, cmd/csaf_downloader/downloader.go, cmd/csaf_provider/actions.go, cmd/csaf_provider/controller.go, cmd/csaf_uploader/main.go, cmd/csaf_validator/main.go, util/file.go, util/file_test.go
=> Replace 'confirming filename' with 'conforming filename'

Makefile
=> Burn v2 version into binaries.

cmd/csaf_checker/processor.go, util/file.go
Solves https://github.com/csaf-poc/csaf_distribution/issues/380
=> Improve error message if filename does not match document/tracking/id and let it be reported by the proper reporter

cmd/csaf_aggregator/config.go, cmd/csaf_aggregator/mirror.go, cmd/csaf_aggregator/processor.go, cmd/csaf_checker/links.go, cmd/csaf_checker/processor.go, cmd/csaf_checker/reporters.go, cmd/csaf_checker/roliecheck.go, csaf/rolie.go
As we are using generics for a while now and we recently introduced
a Set type unify all set operations to that type.
=> Use Set type

cmd/csaf_checker/rules.go
Solves https://github.com/csaf-poc/csaf_distribution/issues/399
=> Allow http redirects

cmd/csaf_checker/config.go, cmd/csaf_checker/main.go, cmd/csaf_checker/processor.go, cmd/csaf_checker/report.go, cmd/csaf_checker/reporters.go, cmd/csaf_downloader/config.go, cmd/csaf_downloader/main.go, docs/csaf_checker.md, internal/options/options.go
=> Add TOML config to checker

cmd/csaf_checker/config.go, cmd/csaf_checker/processor.go, docs/csaf_checker.md
=> Checker: Make time range configurable to check advisories from

cmd/csaf_aggregator/config.go, cmd/csaf_aggregator/main.go, cmd/csaf_checker/config.go, cmd/csaf_downloader/config.go, docs/csaf_aggregator.md
* The last PRs left out the evaluation of the version flag.
* Make Aggregator use the new command line parser.
=> Fix version config and make aggreator use new command line parser.

cmd/csaf_checker/config.go, cmd/csaf_downloader/config.go, cmd/csaf_downloader/downloader.go, cmd/csaf_uploader/main.go, docs/csaf_checker.md, docs/csaf_downloader.md, docs/csaf_uploader.md, internal/certs/certs.go
=> Downloader: Add support for client certificates

docs/csaf_aggregator.md, docs/csaf_checker.md, docs/csaf_downloader.md
=> Document regular expression syntax used for filtering URLs.

cmd/csaf_checker/config.go, cmd/csaf_downloader/config.go, cmd/csaf_uploader/main.go, docs/csaf_aggregator.md, docs/csaf_checker.md, docs/csaf_downloader.md, docs/csaf_uploader.md, docs/examples/aggregator.toml
=> Document potential security issue with plain PEM passwords.

cmd/csaf_checker/processor.go
solves https://github.com/csaf-poc/csaf_distribution/issues/415
=> Error to explaining warning when loading lpmd messages in checker

cmd/csaf_checker/processor.go, cmd/csaf_checker/reporters.go
Solves https://github.com/csaf-poc/csaf_distribution/issues/407
=> Make rolie or directory listing mandatory

cmd/csaf_downloader/config.go
=> downloader: Drop time precision below seconds in log output.

cmd/csaf_downloader/downloader.go
added a callback to log redirects
=> feat: log redirects

cmd/csaf_downloader/stats_test.go
Adds unit tests for counting stats.
=> Downloader: unit tests for stats

docs/csaf_downloader.md
=> Downloader: Document the implementes forward API

docs/scripts/testDownloader.sh
Remove verbose flag from downloader test.
=> Integration Tests: Remove verbose flag from downloader

csaf/validation.go
=> Schema validation: Add AssertFormat flag to schema compiler

docs/csaf_checker.md
=> Checker: Fix  doc of TOML config of validator

README.md, docs/Development.md
=> Docs: Add Development.md

README.md
=> Docs: Fix link to development doc page.

examples/README.md
=> API examples: Improved wording in examples/README.md

cmd/csaf_downloader/downloader.go
Solves https://github.com/csaf-poc/csaf_distribution/issues/511
=> Downloader: Add tlp label to path if no custom directory is configured. Refactor accordingly

util/csv_test.go, util/file_test.go, util/hash_test.go, util/json_test.go, util/set_test.go, util/url_test.go
This is the first batch of new tests that expand the test coverage in the `util` package. Later pull requests will address the unit tests for the `casf` package.
=> Extend unit test coverage in util

csaf/schema/aggregator_json_schema.json
=> fix: bring aggregator schema to errata01

cmd/csaf_checker/reporters.go
This fixes a typo in the error message.
=> Fix typo in error message

docs/provider-setup.md, docs/scripts/DNSConfigForItest.sh, docs/scripts/setupProviderForITest.sh
.. for better access from web applications.
solve #479
=> feat: add access-control-allow-origin header

cmd/csaf_aggregator/config.go, cmd/csaf_aggregator/mirror.go, csaf/advisories.go, docs/examples/aggregator.toml
=> Extend structured logging usage in aggregator

cmd/csaf_aggregator/mirror.go, cmd/csaf_checker/processor.go, cmd/csaf_checker/roliecheck.go, cmd/csaf_downloader/downloader.go, csaf/advisories.go
This should avoid bugs for more complex scenarios.
=> Remove unnecessary URL joins
