gocsaf/csaf

cmd/csaf_provider/files.go

There is no need to use  io.Copy  when writing to a hash.

No need for io.Copy when writing to hash.

---

cmd/csaf_provider/actions.go
cmd/csaf_provider/config.go

Add `upload_limit` option to provider config. Values lesser than 1 means unlimited uploads.

Make CSAF upload size configurable. Defaults to 50MB

---

cmd/csaf_checker/processor.go
cmd/csaf_provider/actions.go
csaf/summary.go
util/json.go

Extracting an essential summary from an advisory is need in provider and aggregator.
So this code is factored out to be useful in both cases.

Factor out summary extraction from advisories.

---

README.md
cmd/csaf_checker/processor.go
cmd/csaf_provider/config.go
cmd/csaf_uploader/main.go
csaf/models.go

* Bump copyright year 2021 -> 2022 on a few files.

Fixing `CASF' typos

---

cmd/csaf_checker/reporters.go

* Remove minor typos.
* Go upper case for HTTPS as this is more common.
* Make texts indicating a good result start with somethink else
than "No", this removes an indirection in thinking and also offers
a visible difference.
* Bump copyright year to 2022.
* Do PGP to "public OpenPGP keys" while at the reporters.go file
while at it (to make merging easier).
* Use an explicit message to indicate that a check is not done because
of a missing implementation.

Improve checker's reporting texts

---

README.md
cmd/csaf_uploader/main.go

* Add "client-cert" and "client-key" flag options to allow the uploader to use
TLS client certificate for authentication with the provider.

Use TLS client certificate for authentication (Uploader)

---

docs/scripts/uploadToProvider.sh

* Remove `let` from the script as it will return 1 (signalling an error) on the
first iteration, which will stop the script when in `set -e` mode.
It also is unnecessary, as the increment can be done at the place of
usage directly.
* Added a "remainder aka modulo" division, otherwise there will be no
TLP option set, once we run out of the four entries in the TLSs
list.
* (Style) remove superfluous semicolons.

Improve integration test uploadToProvider.sh

---

cmd/csaf_checker/processor.go

* In case of errStop, add a message to show which check aborted the others.

Add message to explain a stopped check

---

cmd/csaf_checker/processor.go
cmd/csaf_checker/reporters.go

This PR introduces a type to collect the message of a checker topic.
This removes some awful code duplication and a little strange call
pattern ... ugly left-overs from previous changes.

Type the messages of a checker topic to avoid code duplication.

---

cmd/csaf_provider/create.go

If there is already a security.txt file we add the CSAF line in front of it 
in case it is not already in.
Resolves #35

Update the security.txt

---

cmd/csaf_provider/config.go
cmd/csaf_provider/create.go
docs/provider-setup.md

The branch provider-listed-mirrorred2 implements this.
In the config there is a new optional table provider_metadata with
bool fields list_on_CSAF_aggregators and mirror_on_CSAF_aggregators
which are both are optional. If not set the defaults of the standard are used (true).
The publisher field of the config is moved into the provider_metadata table
as it is on the same level as list and mirror options in the generated provider_metadata.json
file.

For issue #83

---

.github/workflows/release.yml
Makefile

* Add only uploader and checker binaries and basic documentation to windows dist archive.
* Improve Makefile to be able to use github lightweight git tags for release version calculation.
* Change github action to use the `make dist` target for asset uploading.

Improve release process

---

README.md
docs/provider-setup.md
docs/scripts/setupProviderForITest.sh
docs/test-keys/Readme.md

*  Add general hints that this example only shows how the components
work together and that a GNU/Linux admin should be consulted for
a secure setup.
* Adjust the scripts that setup a testing instance to use better
permissions as good example.
* Add a section about security considerations.
* Improve phrasing at a few places.
* Move upload example to use TLS client certificates as recommended.

Improve setup documentation regarding securitry

---

cmd/csaf_checker/main.go
cmd/csaf_uploader/main.go

Remove redundant brackets via `gofmt -r '(a) -> a' -w *.go`.

Remove redundant brackets.

---

docs/csaf_aggregator.md
docs/scripts/testAggregator.sh

* Add hints how to serve the aggregator output using nginx.
* Add hint that the permission of the aggregator config file should be
restricted.
* Add a setuid bit to the aggregator integration test script
to easy manual serving.

Improve aggregator setup docs

---

cmd/csaf_aggregator/indices.go
cmd/csaf_aggregator/mirror.go
cmd/csaf_checker/processor.go
cmd/csaf_provider/actions.go
csaf/rolie.go

Issue hash and signature URLs of advisories in ROLIE feeds, too. 

---

cmd/csaf_aggregator/mirror.go
cmd/csaf_provider/actions.go
cmd/csaf_uploader/main.go

* Change options when creating the armored version of the signature
to leave out the optional headers, which would be `Version:`
and `Comment:`, as it is considered uncommon for a while now to
set these.

Change OpenPGP signatures to be without headers

---

docs/client-certificate-setup.md
docs/scripts/TLSClientConfigsForITest.sh

* Change nginx config to return 403 on unauthorized access to
the non-white TLP locations. We cannot hide the existence anyway,
as it is listed in the provider-metadata.json, even when restricted.

Improve nginx setup docs

---

docs/csaf_provider.md

Added missing examples for already implemented issuing_authorities and contact_details to provider_metadata.publisher in docs/csaf_provider.md. Clarified the TOML definition and linked the toml.io website where Syntax etc. for toml can be looked up.

Add documentation

---

csaf/models.go

Add validation of MetadataVersion and MetadataRole when loading JSON models.
That must be an oversight from the early days of the models.

Add forgotten validation for metadata

---

cmd/csaf_aggregator/config.go
cmd/csaf_aggregator/indices.go
cmd/csaf_provider/actions.go
cmd/csaf_provider/config.go
cmd/csaf_provider/create.go
docs/csaf_aggregator.md
docs/csaf_provider.md
docs/examples/aggregator.toml

Solves #77 
Maybe TODO: Don't allow directory listing of folders containing advisories?

Only create/update index.txt, changes.csv when configured.

---

cmd/csaf_checker/processor.go
cmd/csaf_downloader/downloader.go
csaf/util.go
docs/examples/aggregator.toml

The `csaf.LoadProviderMetadataForDomain` now attempts to load a provider meta data file directly if the URL starts with `https://`
Issue #231

Moved direct loading of pmd from downloader to library.

---

cmd/csaf_checker/links.go
cmd/csaf_checker/processor.go

When running the listing check in the checker inaccessible folders are listed multiple times.
This PR fixes this,

Only report bad directories in listing check only once.

---

csaf/util.go

Solves #252 
Loading the PMD may lead to the same content through different URLs.
Try to minimize validating and error logging based on the checksum
of the PMDs we are already calculating.

Avoid duplicate errors checking and logging when loading pmds.

---

docs/csaf_aggregator.md
docs/provider-setup.md
docs/proxy-provider-for-aggregator.md
docs/scripts/TLSClientConfigsForITest.sh
docs/scripts/setupProviderForITest.sh

* Add docs/proxy-provider-for-aggregator.md with new instructions how to 
publish advisories from  a CSAF publisher manually via the aggregator.
* Link new file from csaf_aggregator-md.
* Improve formatting in some scripts a bit.

Add docs for a provider proxy

---

cmd/csaf_checker/main.go
cmd/csaf_checker/processor.go

Do not die with `log.Fatalf` in the middle of checking when client certs are configured badly.
Check this right at the start.

Load client certs early to detect misconfiguration

---

cmd/csaf_checker/main.go
cmd/csaf_uploader/main.go

Avoid dying hard when loading of the clients certs during creation of an HTTP client. Check the failure at program start like in the checker.
Furthermore use same error message.

Unify loading of client certs in checker and uploader.

---

cmd/csaf_aggregator/indices.go
cmd/csaf_provider/indices.go
util/csv.go

Write field in `change.csv` in double-quotes (`"` ).
Fixes #279

Use fully quoted CSV writer for changes.csv

---

docs/scripts/DNSConfigForItest.sh

* Make nginx only try to map the root (URL /) request to the
provider-metadata.json for DNSPath, otherwise /index.txt  and all other URLs
will also serve that single file.

Improve DNS example and itest setup

---

docs/examples/provider_config.toml

Fixes  https://github.com/csaf-poc/csaf_distribution/issues/291

Fixes canonical url prefix not being quoted and an extra ' at line 67 in the provider_config.toml

---

docs/scripts/prepareUbuntuInstanceForITests.sh

* Make sure that we do not have an old go installation around, because otherwise it maybe broken by untarring the newer one. As documented on https://go.dev/doc/install .

Improve setup script für Ubuntu systems

---

cmd/csaf_checker/main.go
cmd/csaf_checker/processor.go
cmd/csaf_downloader/downloader.go
cmd/csaf_downloader/main.go
docs/csaf_checker.md
docs/csaf_downloader.md
util/client.go

resolves #303 
Adds `-H key:value` command line options to checker and downloader
to use these key/value pairs as additional  header fields in
outgoing HTTP calls.

Add extra http header support to downloader and checker.

---

cmd/csaf_aggregator/mirror.go
cmd/csaf_provider/actions.go
docs/csaf_provider.md
util/json.go

Solves #299 
The result of the `expr:` JSONPaths are now expected to
be strings, arrays of strings or arrays of .. arrays of strings.
The flattened result consists of unique values.

Extract more than one string from expr: category fields.

---

cmd/csaf_aggregator/config.go
docs/csaf_aggregator.md
docs/proxy-provider-for-aggregator.md

* Add term "CSAF proxy provider", because it is mentioned now in
https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html .
* Improve formatting and phrasing.
* Improve description of configuration of update_intervall.
improves #317

Improves aggregator docs

---

cmd/csaf_downloader/downloader.go
cmd/csaf_downloader/main.go
docs/csaf_downloader.md

This PR adds support for remote validation in `csaf_downloader`.
This partly resolves #300

Add remote validator support to downloader

---

cmd/csaf_checker/main.go
cmd/csaf_checker/processor.go
cmd/csaf_checker/report.go
cmd/csaf_checker/reporters.go

Solves #301 
Solves #302 
This PR add two new sections to the report generated by the checker:
1. Valid CSAF document
2. Filename
If no remote validator is configured a respective note  is added to section 1.
Sections 1 and 2 lists the URLs which do not pass the respective tests.
It is noted if there were no tests performed.

Add new requirements 1 and 2 to report

---

cmd/csaf_provider/actions.go
cmd/csaf_uploader/main.go

Enforce `application/json` when uploading advisories to provider.

---

Makefile
README.md

Tested the validator on Windows 10 (successful).
Adds the Validator and its docs into the Windows dist. (Commit 1)
Adds linebreaks into the Makefile to shorten overly long lines. (Commit 2)
Solves https://github.com/csaf-poc/csaf_distribution/issues/326

Validator windows

---

cmd/csaf_aggregator/mirror.go
cmd/csaf_checker/processor.go
cmd/csaf_downloader/downloader.go
cmd/csaf_provider/actions.go
cmd/csaf_validator/main.go
csaf/remotevalidation.go
docs/csaf_aggregator.md
docs/csaf_validator.md

Solves https://github.com/csaf-poc/csaf_distribution/issues/324 by adding the --verbose flag to the csaf_validator.
Calling the validator with the verbose flag but without a remote validator currently has no effect. (The validator behaves as if verbose was not called)

Remote validator output

---

cmd/csaf_aggregator/config.go
cmd/csaf_aggregator/main.go
docs/csaf_aggregator.md
docs/examples/aggregator.toml

Adds option no_lock to csaf_aggregator. If set to true, no lockfile will be used. If no_lock is false, the configs lockfile will be used. If no lockfile is specified, /var/csaf_aggregator/run.lock will be used as default.
Solves https://github.com/csaf-poc/csaf_distribution/issues/344

Lockfile aggregator

---

.github/workflows/go.yml

What:
Add revive action to github actions as described in https://github.com/marketplace/actions/revive-action 
Why:
Revive can catch potential mistakes and poorly written code. Solves  https://github.com/csaf-poc/csaf_distribution/issues/353

Add revive action to workflows

---

cmd/csaf_checker/reporters.go

Give out a warning if no remote validator is configured.
Clarify that the inbuild validator only validates against the schema.
Solves https://github.com/csaf-poc/csaf_distribution/issues/338

Rephrase csaf validation result

---

cmd/csaf_checker/main.go
cmd/csaf_downloader/main.go
docs/csaf_aggregator.md
docs/csaf_checker.md
docs/csaf_downloader.md

* add rate default to download and checker options, using the description field
in the struct tag because we leave the value at nil by default.
* use the same phrasing in the aggregator docs to be consistent
solve #359

doc: improve rate default documentation

---

.github/workflows/go.yml
.github/workflows/itest.yml
.github/workflows/release.yml
cmd/csaf_downloader/downloader.go
cmd/csaf_downloader/main.go
docs/csaf_downloader.md
go.mod

Add `--worker` flag to downloader.
Some sites seems to limit the number of requests per time interval per http client.
This PR adds a flag to download more than one advisory at once via multiple
http clients to speed up the process. By default only two clients are used.
Furthermore this PR also adds the feature to stop the downloader by `Ctrl-C`ing.
When the `ignoresigcheck` flag is set the results of the signature checks are ignored.
Bumped Go to 1.20 to use `errors.Join`.

Add concurrent downloads to downloader.

---

cmd/csaf_aggregator/mirror.go
cmd/csaf_checker/processor.go
cmd/csaf_downloader/downloader.go
cmd/csaf_provider/actions.go
cmd/csaf_uploader/main.go
cmd/csaf_validator/main.go
util/file.go

Implement #325: Check that the filename matches the ID according to the
rules in Section 5.1. All places where the code already checks the
filename syntax the code now checks that it also matches the ID.
There's one exception to this in the `csaf_uploader` where the this
additional check is only done when schema checks are enabled. That was
done for simplicity of implementation because only in that case does the
uploader parse the CSAF file.

Check that filename matches /document/tracking/id

---

README.md

We need at least Go 1.20 but the README still talks about 1.19.1.
This PR is fixing this.

We need at least Go 1.20

---

cmd/csaf_checker/processor.go
cmd/csaf_checker/reporters.go

Currently, trying to check an invalid provider-metadata.json leads to a crash. (It causes a nullpointerreference when ranging over *domain.Role in line 250 of csaf_checker/processor.go): 
for _, r := range buildReporters(*domain.Role) {
r.report(p, domain)
}
This PR adds logging output that the provider-metadata.json of that domain couldn't be parsed and then continues onto the next domain instead of trying to build relevant reporters.
This should also address https://github.com/csaf-poc/csaf_distribution/issues/251

Fix pmd crash

---

cmd/csaf_checker/processor.go
cmd/csaf_checker/roliecheck.go

Currently the check on proper access-protectedness is done via checking the TLP-level of the feed. Any advisory placed within the wrong feed would potentially be missed or misdiagnosed.  This PR causes the check to check for the TLP-level of the advisory instead.

Check for advisoryLabel instead of feedlabel

---

cmd/csaf_checker/roliecheck.go

Bug: We used string comparison to rank tlp levels in the rolie label checker.
`case label >= csaf.TLPLabelAmber:` with label = `csaf.TLPLabelWhite`
is the same as `case "WHITE" > "AMBER":` which is obviously not intended.
Fix: Use the `tlpLevel` function on the labels before the comparison.

Dont use string comparison to rank labels.

---

cmd/csaf_downloader/config.go
cmd/csaf_downloader/downloader.go
cmd/csaf_downloader/main.go
docs/csaf_downloader.md

First step towards storing options in configuration files.
Part of  #396

Add support for config files in downloader.

---

cmd/csaf_downloader/config.go
cmd/csaf_downloader/main.go
docs/csaf_downloader.md

As we need more complex configuration in the downloader (and checker) with per domain options switch to TOML as config file format in the checker.

Use TOML as config file format in downloader

---

cmd/csaf_aggregator/mirror.go
cmd/csaf_downloader/config.go
cmd/csaf_downloader/downloader.go
csaf/advisories.go
docs/csaf_downloader.md
internal/models/models.go

Downloader: Make time range configurable to download advisories from

---

cmd/csaf_checker/config.go
cmd/csaf_checker/processor.go
docs/csaf_checker.md

Checker: ignore advisories by given patterns

---

cmd/csaf_aggregator/config.go
docs/csaf_aggregator.md
docs/examples/aggregator.toml

Aggregator: Add support for client certificates and extra header

---

cmd/csaf_checker/config.go
cmd/csaf_checker/processor.go
docs/csaf_checker.md
internal/models/models.go

Checker: remove years flag

---

cmd/csaf_aggregator/config.go
cmd/csaf_aggregator/mirror.go
docs/csaf_aggregator.md
docs/examples/aggregator.toml

Aggregator: Add time range filtering

---

docs/scripts/prepareUbuntuInstanceForITests.sh

Currently, trying to set up a blank Ubuntu 20.4 Instance via prepare prepareUbuntuInstanceForITests.sh will fail since 
curl https://go.dev/VERSION\?m=text currently returns 
go1.21.0
time 2023-08-04T20:14:06Z
The timestamp setting the latest_go variable to an unusable state, causing the depending curl instance to throw a syntax error.
This PR will exclude the timestamp and allows fetching the correct go version.

No longer set timestamp of version as part of go version in prepareUbuntuInstanceForITests

---

.github/workflows/go.yml
.github/workflows/itest.yml
.github/workflows/release.yml
README.md
cmd/csaf_downloader/config.go
cmd/csaf_downloader/downloader.go
cmd/csaf_downloader/forwarder.go
cmd/csaf_downloader/main.go
cmd/csaf_uploader/processor.go
docs/csaf_downloader.md
go.mod
internal/misc/doc.go
internal/misc/mime.go

Downloader: Add forwarding to HTTP endpoint

---

cmd/csaf_downloader/config.go
cmd/csaf_downloader/forwarder.go
cmd/csaf_downloader/main.go
docs/csaf_downloader.md

downloader: Fix logging docs and some comments

---

cmd/csaf_checker/processor.go

Part of https://github.com/csaf-poc/csaf_distribution/issues/438
Currently, any file discrepancies between the different file retrieval methods is reported in integrity.
This PR changes the checker so it reports any file missing from a list in their respective retrieval methods Requirement

Checker: Fix checking of missing files

---

.github/workflows/release.yml

* use `ubuntu-20.04` so we get binaries that are more compatible with elder GNU/Linux distribution, because go binaries link to glibc (for some operating system operations like dns).
resolve #456

Change release action to use elder Ubuntu runner

---

cmd/csaf_downloader/config.go
cmd/csaf_downloader/downloader.go
cmd/csaf_downloader/forwarder.go
docs/csaf_downloader.md
internal/options/log.go
internal/options/log_test.go
util/client.go

* The `verbose` flag is removed from the downloader. To get the previous output use `loglevel=debug`.
* Fixed config of `loglevel` and `logfile`
* The logging http client now supports structured logging, too.
Solves #457

Downloader: Remove verbose flag

---

cmd/csaf_downloader/forwarder.go
cmd/csaf_downloader/forwarder_test.go

Bring coverage of forwarder near 100%.
The remaining untested error paths belong to the fact that
we build the requests to the remote server in memory
with no limitations. In the future we may limit this but we
should do this earlier in the pipeline.

Downloader: unit test forwarder

---

cmd/csaf_checker/processor.go
internal/models/models.go
internal/models/models_test.go

Checker: Fix year folder check

---

docs/csaf_aggregator.md
docs/csaf_checker.md
docs/csaf_downloader.md

* add a documentation section to the downloader docs for the timerange-option.
* point aggregator and checker docs to the downloader section for timerange.

docs: improve timerange documentation

---

cmd/csaf_aggregator/config.go
cmd/csaf_downloader/config.go
cmd/csaf_downloader/downloader.go

* use full name for printing out the used logfile for the downloader.
* for debug or verbose, log the timeintervall that will be used for downloader and aggregator. (The checker has this as part of its output already.)

fix: improve logging for downloader and aggregator

---

docs/csaf_downloader.md
internal/models/models.go
internal/models/models_test.go

Solves #480 .. at least integer values for years, days and month. The fractional cases like `1.5y` are omitted as they are more complex.

Time ranges: Accept days, months and years

---

docs/csaf_provider.md
go.mod
go.sum
util/json.go

As https://github.com/PaesslerAG/jsonpath/pull/39 is still pending we use our fork
till upstream is moving forward.

Use Intevation's JSONPath fork

---

csaf/advisory.go
examples/purls_searcher/main.go

Extract purls from relationships in purls_searcher example.
Solves #486

API: Fix pattern matching of purls and document categories in advisory model

---

cmd/csaf_aggregator/config.go
cmd/csaf_checker/config.go
cmd/csaf_downloader/config.go
cmd/csaf_uploader/config.go
cmd/csaf_validator/main.go
docs/csaf_aggregator.md
docs/csaf_checker.md
docs/csaf_downloader.md
docs/csaf_uploader.md
docs/csaf_validator.md
docs/examples/aggregator.toml
docs/scripts/testChecker.sh
docs/scripts/uploadToProvider.sh

Solves https://github.com/csaf-poc/csaf_distribution/issues/494

Convert a lot of command line arguments to snake case

---

Makefile
README.md

Add build for macOS

---

cmd/csaf_checker/processor.go
cmd/csaf_checker/reporters.go
csaf/providermetaloader.go

If we don't find the security.txt in the well-known folder try to find it under https://domain/security.txt as a fallback.
Solves #503

PMD: Support legacy security.txt location as fallback.

---

csaf/generate_cvss_enums.go

In the generator to create the cvss enums  the `slices` (Go 1.21) package was used.
Replaced it with Go 1.20 compatible code.

Go 1.20 compat: Remove usage of slices in enum generator.

---

cmd/csaf_checker/processor.go
csaf/advisories.go
internal/models/models.go
internal/models/models_test.go

Solves #518 
Now uses the `updated` field of ROLIE feed entries instead of the `published` field.
Drop time filtering in checker by folder year as this name stems from the publishing year
and not the latest update.

Advisories: Time filter download by 'updated' field in ROLIE entries.

---

cmd/csaf_checker/processor.go

In issue #522 there are signs that the checker get mixed up when checking multiple domains.
One possible reason could be the not proper reset of the processor before checking
a particular. This PR guarantees that the reset is done before the check.
Maybe fixes #522

Checker: Ensure that the processor is reset before checking each domain.

---

README.md

* Add overview link to csaf.io
* Fix link to specification and add link to the latest errata document.

docs: improve link to CSAF standard documents

---

cmd/csaf_downloader/config.go
cmd/csaf_downloader/downloader.go
cmd/csaf_downloader/main.go
csaf/providermetaloader.go
docs/csaf_aggregator.md
docs/csaf_provider.md

This PR addresses #520. It adds an enumerate method to the providermetaloader.go which loads the PMDs from the well-known path, the security.txt, or the DNS URL (as defined in the spec in [requirement 7.3.1](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#731-finding-provider-metadatajson)).
The PR also includes usage of the new method in the csaf_downloader and its main method.
There is, however, still a doubt that I have about the issue: Why does the load method compare the PMD from the well-known path to the first one found in the security.txt? I couldn't find a respective requirement in the spec. It could be the case that a provider provides the PMD in the well-known path and only advertises additional PMDs in the security.txt, right?
Looking forward to your feedback!

Print provider-metadata.json files per domain

---

README.md

- Fix grammar and enhance wording.
- Consecutive web-links without non-linked, non-whitespace characters are … problematic; thus rectified.
- References to outdated specifications do not make much sense, hence omitted, especially as the link to the current specification immediately followed.

[README.md] Enhance linking and grammar

---

LICENSES/BSD-3-Clause.txt
csaf/cvss20enums.go
csaf/cvss3enums.go
csaf/generate_cvss_enums.go
csaf/schema/cvss-v2.0.json.license
csaf/schema/cvss-v3.0.json.license
csaf/schema/cvss-v3.1.json.license

* change generate_cvss_enums.go to note that the input file is relevant for the license.
* change license and copyright of cvss20enums.go and cvss3enums.go to BSD-3-Clause and FIRST.
* add reuse.software 3.0 compatible files for the schema cvss files.
resolves #534

docs: fix licensing info for generated files

---

cmd/csaf_downloader/downloader.go

`util.PathEval` objects are intended to be used single threaded.
Therefore sharing one for all workers in the downloader is causing data races.
This PR addresses this.

Remove data races in downloader caused by shared use of json path eval.

---

cmd/csaf_aggregator/processor.go
cmd/csaf_downloader/downloader.go
csaf/providermetaloader.go

Fix: don't drop error messages from loading provider-metadata.json
Additionally removed the duplicate check of provider metadata candidates retrieved from `security.txt`.
Previously in case of trying last resort dns, all other error messages were dropped.

Fix missing error messages from loading provider-metadata.json

---

cmd/csaf_downloader/downloader.go

Minor fix of the error message returned on an invalid provider metadata json in the csaf downloader.
The error message had a trailing `:` which suggest that there are some details which were truncated. However the details are already printed before in the log.
The extra `:` was accidentally added in #531

fix error message in csaf downloader

---

docs/scripts/Readme.md
docs/scripts/setupValidationService.sh

Currently you need to be root to use the setupscripts as described. This will allow users with sudo privileges to use the setup scripts as well.

feat: no longer require to be root user to call setup scripts

---

cmd/csaf_aggregator/config.go
cmd/csaf_checker/processor.go
cmd/csaf_downloader/downloader.go
cmd/csaf_downloader/forwarder.go
docs/csaf_aggregator.md
docs/csaf_checker.md
docs/csaf_downloader.md
util/client.go

Use a default user agent

---

cmd/csaf_checker/processor.go
cmd/csaf_downloader/downloader.go

Warn if no fingerprint is specified and give more details if fingerprint comparison fails. This pull request does not change the API and cannot differentiate if an empty or no fingerprint is provided.

Improve PGP fingerprint handling

---

docs/development-ca.md
docs/scripts/setupProviderForITest.sh

`.local` is reserved for local-area networks, and `.localhost` is reserved for loopback devices. Using `.test` allows easier usage for different test setups.

Use .test TLD for integration setup

---

docs/scripts/prepareUbuntuInstanceForITests.sh

Add zip as package to be installed in preparation step as the `make dist` target uses it.

improve test setup scripts by adding missing package

---

Makefile

* Change Makefile to remove the leading `v` from the git tag
in the case of release tags. Previously this was only done for
pre-release git tags.

fix: build-in version for release tags 

---

docs/csaf_downloader.md

solves https://github.com/gocsaf/csaf/issues/589

Fix: Update downloader docs

---

cmd/csaf_aggregator/config.go
cmd/csaf_checker/processor.go
cmd/csaf_downloader/downloader.go
cmd/csaf_downloader/forwarder.go
cmd/csaf_uploader/processor.go

This merge request resolves [Issue 596](#596)  by ensuring that all HTTP and HTTPS traffic uses the proxy configuration specified in the environment variables (`HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`).
- Updated all instances of `http.Transport` to include the `Proxy` field:
```go
Proxy: http.ProxyFromEnvironment
```
- Ensured compatibility with existing `TLSClientConfig` settings, preserving secure connections.
The issue described in [Issue 596](#596) identified a shortfall where proxy settings were ignored, causing failures in proxied environments. This fix ensures compliance with Go's standard proxy behavior and improves usability for users in corporate or secured networks.
1. **Environment Setup**:
- Configured proxy settings using `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY`.
- …

ensure HTTP requests use proxy env vars

---

cmd/csaf_provider/controller.go

* Remove `charset=utf-8` parameter, which is not allowed for JSON, according to rfc8259.
Reported in  https://github.com/gocsaf/csaf/issues/588#issuecomment-2548116924 by @Rafiot

fix: Content-Type header for JSON responses (minor)

---

cmd/csaf_validator/main.go
docs/csaf_validator.md

Prints a warning if no remote validator was configured.
Closes #601

Warn if no remote validator was specified

---

LICENSE-Apache-2.0.txt

This allows other programs like google/licensecheck to correctly detect the license. This is required to display the documentation in `pkg.go.dev`.

Add Apache 2.0 license to root folder

---

README.md

Use https://oasis-open.github.io/csaf-documentation/ as long as https://csaf.io/ still has DNS problems.

Update README.md to exchange csaf.io until it is fixed

---

cmd/csaf_checker/processor.go

Closes https://github.com/gocsaf/csaf/issues/411
Originally, the checker would fail if any of its checks failed. Since only one of the requirements 8-10 is mandatory, whether one of those checks would give out an error or a warning was dependent on the other two checks and they would only fail if all would fail. 
This no longer holds true for the current design of the checker since c7453a644825ddbb1a5c81a8934a82f2af521630. 
The current design of these three checks lead to e.g. https://github.com/gocsaf/csaf/issues/411, so by modernizing the checkWellknownSecurityDNS function as well as its subfunctions this issue is fixed.

Errors for lookup checks

---

.github/workflows/itest.yml
.github/workflows/release.yml
README.md
docs/Development.md

* Update runner to ubuntu-22.04 which is the eldest to be supported
by github from 2025-04-01.
* Update github actions and go version for release and itest workflows.
* Update current go revision to Readme and development docs.
resolve #614

update runner for release to 22.04, other actions and go version, thus also newer glibc

---

examples/product_lister/main.go

This example demonstrates how to iterate all product IDs and retrieve their corresponding product identification helper and full product name. It also demonstrates an iteration of all product identification helper with their corresponding product ID.
Closes #566

Add example for iterating product id and product helper

---

cmd/csaf_aggregator/client.go

1. According to standard library the client must close the Body of http response. The function [downloadJSON()](https://github.com/gocsaf/csaf/blob/main/cmd/csaf_aggregator/client.go) in the csaf_aggregator defers the `Body.Close()` after some checks are made and an early return that may return even when `c.Get()` does not return an error. This is where the `res.Body` might not be closed.
2. Besides that either I didn't get the idea behind the return via a call to a closure or it should be simplified.
3. Do not drop the err details from `c.Get()` but give them more context. See Go Blog: _[It is the error implementation’s responsibility to summarize the context.](https://go.dev/blog/error-handling-and-go)_

Fix potential leak of HTTP response body in downloadJSON

---

cmd/csaf_checker/processor.go
cmd/csaf_checker/processor_test.go
internal/testutil/testutil.go

Some providers don't correctly return the content type for the advisories. Report an error in the checker to make this defect more visible. The downloader currently displays a warning.
Closes #606

Report error in checker if content type is not correct

---

cmd/csaf_aggregator/indices.go
cmd/csaf_aggregator/mirror.go
cmd/csaf_aggregator/processor.go

Parts of the URL were not path escaped. This results in a wrong URL; if the provider name contains characters that need to be escaped.

Fix aggregator URL handling

---

.github/workflows/go.yml

We use Revive already which is a replacement for golint and golint isn't maintained anyway.

Remove golint github action

---

README.md
csaf/doc.go

* Deemphazise the old repo link alert.
* Add more hints about officially unsupported but possible use as library.
solve #634

docs: improve README.md

---

cmd/csaf_checker/links.go

Correctly handle URLs that are absolute.
Related: #661

Fix csaf checker listed check

---

Makefile

for modified git workspaces a `-modified` is added to the semantic version
in the makefile.

improve calculated version numbers

---

docs/csaf_provider.md

* add a "both" to explain the config file option `certificate_and_password` better.
Here is the code that shows that it works like this for easier reviewing: https://github.com/gocsaf/csaf/blob/ae184eb189e15c179e2ba618f21d3ae72363222b/cmd/csaf_provider/controller.go#L97-L103
apply after #667

improve docs (minor) for csaf_provider

---

internal/misc/json.go

Fix doc comment: remove untrue claim of disallowing unknown json fields in helper function.
Looks like a bug otherwise, but is the intended behavior: 
See commit https://github.com/gocsaf/csaf/pull/655/commits/7935818600ee70cbcb7784a67788a4f3bacaba01 of PR #655 .

fix doc comment: remove untrue claim of disallowing unknown fields

---

internal/misc/json.go

Re-add the unknown fields check. Will supersede https://github.com/gocsaf/csaf/pull/677
Explanation:
Original comment https://github.com/gocsaf/csaf/pull/677#issue-3393355709 was referring to was based on a misunderstanding. 
From my current understanding, https://docs.oasis-open.org/csaf/csaf/v2.0/cs02/csaf-v2.0-cs02.html#6220-additional-properties specifies additional properties are not allowed.
The reason this was not changed within the code was that additional properties are already flagged during the JSON-schema check and would already lead to an error even if not checked there again.
However, it should be checked here.

Re-add unknown fields check
